#!/usr/bin/env bash
# Deploy JamboPlus API to Railway and sync Flutter app configs.
#
# Usage:
#   ./scripts/deploy-railway.sh              # deploy + update app URLs + health check
#   ./scripts/deploy-railway.sh --setup      # first-time: vars, volume, domain, deploy
#   ./scripts/deploy-railway.sh --vars-only  # push env vars to Railway (no deploy)
#   ./scripts/deploy-railway.sh --url-only   # refresh Flutter URLs from Railway domain
#   ./scripts/deploy-railway.sh --build-apk  # deploy + build release APKs
#
# First time:
#   cp scripts/railway.env.example scripts/railway.env
#   railway login
#   ./scripts/deploy-railway.sh --setup

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/scripts/railway.env"
SERVER_DIR="$ROOT/server"

MODE="deploy"
for arg in "$@"; do
  case "$arg" in
    --setup) MODE="setup" ;;
    --vars-only) MODE="vars" ;;
    --url-only) MODE="url" ;;
    --build-apk) MODE="build" ;;
    -h|--help)
      sed -n '2,14p' "$0"
      exit 0
      ;;
  esac
done

log() { echo "▸ $*"; }
die() { echo "✗ $*" >&2; exit 1; }

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
  fi
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing '$1'. Install it first."
}

load_env() {
  if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    set -a && source "$ENV_FILE" && set +a
    log "Loaded $ENV_FILE"
  elif [[ "$MODE" == "setup" || "$MODE" == "vars" || "$MODE" == "deploy" || "$MODE" == "build" ]]; then
    log "No scripts/railway.env — copy scripts/railway.env.example and edit secrets"
  fi
}

ensure_railway_cli() {
  require_cmd railway
  if ! railway whoami >/dev/null 2>&1; then
    log "Login to Railway (browser will open)…"
    railway login
  fi
  log "Railway user: $(railway whoami 2>/dev/null | head -1 || true)"
}

ensure_linked() {
  cd "$SERVER_DIR"
  if ! railway status >/dev/null 2>&1; then
    log "Linking Railway project (run from server/)…"
    if [[ -n "${RAILWAY_PROJECT_ID:-}" ]]; then
      railway link -p "$RAILWAY_PROJECT_ID" ${RAILWAY_SERVICE:+-s "$RAILWAY_SERVICE"}
    else
      log "Choose existing project or create new:"
      railway link || railway init -n jamboplus
    fi
  fi
  log "Project: $(railway status 2>/dev/null | head -5 || true)"
}

generate_secrets() {
  [[ -z "${JWT_SECRET:-}" ]] && JWT_SECRET="$(random_hex)" && log "Generated JWT_SECRET"
  [[ -z "${APP_API_SECRET:-}" ]] && APP_API_SECRET="$(random_hex)" && log "Generated APP_API_SECRET"
  [[ -z "${APP_API_KEY:-}" ]] && APP_API_KEY="jamboplus-prod-key"
  [[ -z "${ADMIN_PASSWORD:-}" ]] && ADMIN_PASSWORD="Admin@Jambo2026!"
  [[ -z "${DB_PATH:-}" ]] && DB_PATH="/data/jamboad.db"
  [[ -z "${HOST:-}" ]] && HOST="0.0.0.0"
}

save_env_file() {
  cat > "$ENV_FILE" <<EOF
# Generated by deploy-railway.sh — do not commit
RAILWAY_PUBLIC_URL=${RAILWAY_PUBLIC_URL:-}
JWT_SECRET=$JWT_SECRET
APP_API_SECRET=$APP_API_SECRET
APP_API_KEY=$APP_API_KEY
ADMIN_PASSWORD=$ADMIN_PASSWORD
DB_PATH=$DB_PATH
HOST=$HOST
BUILD_RELEASE_APK=${BUILD_RELEASE_APK:-false}
EOF
  chmod 600 "$ENV_FILE"
  log "Saved scripts/railway.env"
}

push_variables() {
  cd "$SERVER_DIR"
  local args=(
    "JWT_SECRET=$JWT_SECRET"
    "DB_PATH=$DB_PATH"
    "HOST=$HOST"
    "APP_API_KEY=$APP_API_KEY"
    "APP_API_SECRET=$APP_API_SECRET"
    "ADMIN_PASSWORD=$ADMIN_PASSWORD"
  )
  log "Setting Railway variables…"
  railway variable set "${args[@]}" --skip-deploys
}

ensure_volume() {
  cd "$SERVER_DIR"
  if railway volume list 2>/dev/null | grep -q "/data"; then
    log "Volume /data already exists"
    return
  fi
  log "Adding persistent volume at /data…"
  railway volume add --mount-path /data || log "Volume add skipped (may already exist or need dashboard)"
}

ensure_domain() {
  cd "$SERVER_DIR"
  if [[ -n "${RAILWAY_PUBLIC_URL:-}" ]]; then
    log "Using RAILWAY_PUBLIC_URL from env: $RAILWAY_PUBLIC_URL"
    return
  fi

  local domain=""
  if domain="$(railway domain --json 2>/dev/null | node -e "
    let d=''; process.stdin.on('data',c=>d+=c);
    process.stdin.on('end',()=> {
      try {
        const j=JSON.parse(d);
        const v=j.domain||j.url||j.host||'';
        process.stdout.write(String(v).replace(/^https?:\\/\\//,''));
      } catch { process.exit(1); }
    });
  " 2>/dev/null)" && [[ -n "$domain" ]]; then
    RAILWAY_PUBLIC_URL="https://$domain"
    log "Railway domain: $RAILWAY_PUBLIC_URL"
    return
  fi

  log "Generating Railway public domain…"
  local out
  out="$(railway domain 2>&1 || true)"
  domain="$(echo "$out" | grep -oE '[a-zA-Z0-9.-]+\.up\.railway\.app' | head -1 || true)"
  if [[ -n "$domain" ]]; then
    RAILWAY_PUBLIC_URL="https://$domain"
    log "Railway domain: $RAILWAY_PUBLIC_URL"
  else
    log "Could not detect domain automatically. Set RAILWAY_PUBLIC_URL in scripts/railway.env"
    echo "$out"
  fi
}

deploy_server() {
  # Railway rootDirectory is `server`, so the upload archive must contain a
  # top-level `server/` folder (plain `cd server && railway up` fails unpack).
  local staging
  staging="$(mktemp -d /tmp/jamboplus-railway-XXXXXX)"
  mkdir -p "$staging/server"
  rsync -a \
    --exclude node_modules \
    --exclude data \
    --exclude .env \
    --exclude '*.log' \
    "$SERVER_DIR/" "$staging/server/"
  log "Deploying API to Railway (nested server/ archive)…"
  (
    cd "$staging"
    railway up -d -m "jamboplus api deploy"
  )
  rm -rf "$staging"
  log "Deploy triggered — check: railway logs (from server/)"
}

fetch_public_url() {
  if [[ -n "${RAILWAY_PUBLIC_URL:-}" ]]; then
    return
  fi
  cd "$SERVER_DIR"
  local domain
  domain="$(railway variable list -k 2>/dev/null | grep -E '^RAILWAY_PUBLIC_DOMAIN=' | cut -d= -f2- | tr -d '\r' || true)"
  if [[ -n "$domain" ]]; then
    RAILWAY_PUBLIC_URL="https://$domain"
  else
    ensure_domain
  fi
}

wait_for_health() {
  [[ -z "${RAILWAY_PUBLIC_URL:-}" ]] && return 0
  local url="${RAILWAY_PUBLIC_URL%/}/health"
  log "Waiting for $url …"
  for i in $(seq 1 30); do
    if curl -sf "$url" >/dev/null 2>&1; then
      log "Health OK: $(curl -sf "$url")"
      return 0
    fi
    sleep 5
  done
  die "Health check failed after 150s — run: cd server && railway logs"
}

update_flutter_apps() {
  fetch_public_url
  [[ -z "${RAILWAY_PUBLIC_URL:-}" ]] && die "Set RAILWAY_PUBLIC_URL in scripts/railway.env"
  bash "$ROOT/scripts/update-app-urls.sh" "$RAILWAY_PUBLIC_URL"
}

build_release_apks() {
  fetch_public_url
  [[ -z "${RAILWAY_PUBLIC_URL:-}" ]] && die "Need RAILWAY_PUBLIC_URL for release builds"
  require_cmd flutter

  log "Building JamboPlus release APK…"
  (
    cd "$ROOT"
    flutter build apk --release \
      --dart-define="JAMBO_API_URL=$RAILWAY_PUBLIC_URL" \
      --dart-define="JAMBO_APP_SECRET=$APP_API_SECRET"
  )

  log "Building JamboAd release APK…"
  (
    cd "$ROOT/adplus"
    flutter build apk --release \
      --dart-define="JAMBOAD_API_URL=$RAILWAY_PUBLIC_URL"
  )

  log "APKs:"
  log "  $ROOT/build/app/outputs/flutter-apk/app-release.apk"
  log "  $ROOT/adplus/build/app/outputs/flutter-apk/app-release.apk"
}

# --- main ---

require_cmd curl
require_cmd sed
load_env
ensure_railway_cli

case "$MODE" in
  url)
    ensure_linked
    fetch_public_url
    update_flutter_apps
    exit 0
    ;;
  vars)
    ensure_linked
    generate_secrets
    push_variables
    save_env_file
    log "Variables updated (no deploy)"
    exit 0
    ;;
esac

ensure_linked
generate_secrets

if [[ "$MODE" == "setup" ]]; then
  ensure_volume
  ensure_domain
fi

push_variables
deploy_server
fetch_public_url
save_env_file
wait_for_health
update_flutter_apps

if [[ "$MODE" == "build" || "${BUILD_RELEASE_APK:-false}" == "true" ]]; then
  build_release_apks
fi

echo ""
echo "✓ Done"
echo "  API:    ${RAILWAY_PUBLIC_URL:-<set RAILWAY_PUBLIC_URL>}"
echo "  Admin:  admin@jamboad.co.tz / ${ADMIN_PASSWORD:-<see railway.env>}"
echo "  Secret: APP_API_SECRET in scripts/railway.env (use as JAMBO_APP_SECRET in app builds)"
echo ""
echo "Local dev:  ./scripts/run-local.sh"
echo "Redeploy:   ./scripts/deploy-railway.sh"
echo "Logs:       cd server && railway logs"
